# https://artifacthub.io/packages/helm/argo/argo-cd/9.3.7
# helm repo add argo https://argoproj.github.io/argo-helm
# helm upgrade argocd argo/argo-cd -n argocd -f ./base/argocd/argocd.yaml --version 9.3.7

fullnameOverride: argocd
configs:
  cm:
    kustomize.buildOptions: --enable-helm=true
  params:
    server.insecure: true
  secret:
    # ID admin / PW admin1!
    # htpasswd -nbBC 10 "" admin1! | tr -d ':\n' | sed 's/$2y/$2a/'
    argocdServerAdminPassword: $2a$10$Hkn7gpjEqu2U.6da00/l4ODc7ayz.ps70E/LeoiyeGsqHjlR/LkiO
notifications:
  enabled: false
server:
  service:
    type: NodePort
    nodePortHttp: 30002