#  kaf ./helmtest/application/argocd.yaml -n argocd
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  sources:
    - repoURL: oci://ghcr.io/argoproj/argo-helm/argo-cd
      targetRevision: 9.3.7
      helm:
        valueFiles:
          - $values/helmtest/values/argocd-values.yaml
    - repoURL: https://github.com/nasir17git/multiscc.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/nasir17git/multiscc.git
      path: ./helmtest/single
      targetRevision: main
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
